### ISSUE TITLE
400 - Display page not found. Please check the page exists.

### ISSUE THREAD

**Issue by nurikabe** [finanalyst/grav-plugin-tingle-form#1]
Plugin seem to work great, but getting this error on submit.  Do we need to tell the form to return to the current route?

Sorry for the newbie questions.  Just started playing around with Grav.

**Comment by nurikabe** [comment]
BTW, seems to only be a problem when logged in to the admin plugin.

**Comment by finanalyst** [comment]
Sorry for the delay. It seems all my github notifications were going to spam :(  
Is this still a problem?   
The plugin was not designed to be used in conjunction with the admin plugin.

**Comment by nurikabe** [comment]
Still seems to be an issue, FYI.

Won't be using this while logged in of course so no big deal.
