### ISSUE TITLE
popCont needs setting to raw

### ISSUE THREAD

**Issue by danjames68** [finanalyst/grav-plugin-tingle-form#3]
Hi, this wasn't working for me until I set `popCont` to raw in the template. 

`{{ tform }}_Modal.setContent('{{ popCont|raw }}');`

instead of 

`{{ tform }}_Modal.setContent('{{ popCont }}');`

**Comment by finanalyst** [comment]
Thanks.

**Comment by danjames68** [comment]
Thanks Richard!
