### ISSUE TITLE
Missing dependency: grav-plugin-shortcode-core

### ISSUE THREAD

**Issue by martinzbinden** [finanalyst/grav-plugin-tingle-form#4]
This plugin should be installed automatically for shortcode to work.

Is it possible to place a modal popup without shortcode? As a url per example?

**Comment by finanalyst** [comment]
I dont understand 'should be installed automatically'? Why automatically?
This plugin gives access to a JS functionality that is not part of Grav CMS. So question should be to Grav CMS team, not plugin maintainer.
