### ISSUE TITLE
strange rendering for button

### ISSUE THREAD

**Issue by fugo** [finanalyst/grav-plugin-tingle-form#6]
Something went wrong with the button rendering. 
In Markdown page (Quark default.md) I use `Open  [popup-form form="APopupForm"]a modal form[/popup-form]` but the output in HTML is: `</temporary-tag>` (see screenshot).

![output](https://i.imgur.com/wDfGW1k.png)

Shortcode Core  v5.1.1
Grav 1.7.31

**Comment by finanalyst** [comment]
This seems to be related to an update of Quark.

**Comment by fugo** [comment]
Sorry, I had to do this first. :roll_eyes: 
After deactivating the plugins I found the error.
The **Markdown Typography Plugin**  https://github.com/n-parsons/grav-plugin-markdown-typography produce the wrong HTML tag.

**Comment by fugo** [comment]
Your plugin works great also with the new version of Grav ( v1.7.32 - Admin v1.10.32 )
Thank you!
